.PHONY: clean

clean:
	rm -f ../model_output/*.csv
	rm -f ../figures/*.png
	rm -f figures/*.pdf

.created-dirs:
	mkdir -p ../model_output
	mkdir -p ../figures
	touch .created-dirs

# Pre-processing: clean up survival curves
